import { CountdownPreset } from './types';

export const COUNTDOWN_PRESETS: CountdownPreset[] = [
  {
    id: 'fasting-72',
    title: '72h Fasting',
    icon: '🍵',
    description: 'Three-day fasting protocol countdown.',
    mode: 'countdown',
    defaultDurationDays: 3,
    recurrence: 'none',
    themeId: 'minimal',
    progressVisual: 'bar',
    notes: 'Hydrate and rest. Track milestones every 12 hours.',
  },
  {
    id: 'sobriety',
    title: 'Sobriety Streak',
    icon: '💧',
    description: 'Count up from your sobriety start date.',
    mode: 'countup',
    defaultDurationDays: 365,
    recurrence: 'none',
    themeId: 'swiss',
    progressVisual: 'ring',
    notes: 'Stay focused day by day.',
  },
  {
    id: 'smoke-free',
    title: 'Smoke-Free',
    icon: '🚭',
    description: 'Track smoke-free time since your quit date.',
    mode: 'countup',
    defaultDurationDays: 365,
    recurrence: 'none',
    themeId: 'aqua',
    progressVisual: 'ring',
    notes: 'Celebrate each week of progress.',
  },
  {
    id: 'christmas',
    title: 'Christmas',
    icon: '🎄',
    description: 'Annual Christmas countdown.',
    mode: 'countdown',
    defaultDurationDays: 300,
    recurrence: 'yearly',
    themeId: 'retro',
    progressVisual: 'bar',
    notes: 'Automatically repeats every year.',
  },
  {
    id: 'birthday',
    title: 'Mom’s Birthday',
    icon: '🎂',
    description: 'A recurring yearly birthday reminder.',
    mode: 'countdown',
    defaultDurationDays: 180,
    recurrence: 'yearly',
    themeId: 'swiss',
    progressVisual: 'ring',
    notes: 'Keep gifts and plans in notes.',
  },
  {
    id: 'vacation',
    title: 'Next Vacation',
    icon: '🏝️',
    description: 'Countdown to your trip start date.',
    mode: 'countdown',
    defaultDurationDays: 90,
    recurrence: 'none',
    themeId: 'aqua',
    progressVisual: 'bar',
    notes: 'Perfect for travel prep and packing deadlines.',
  },
  {
    id: 'project-deadline',
    title: 'Project Deadline',
    icon: '🚀',
    description: 'Keep your launch date visible every day.',
    mode: 'countdown',
    defaultDurationDays: 45,
    recurrence: 'none',
    themeId: 'grid',
    progressVisual: 'ring',
    notes: 'Split into milestones and monitor daily.',
  },
  {
    id: 'exam-day',
    title: 'Exam Day',
    icon: '🧠',
    description: 'Time left before a key exam.',
    mode: 'countdown',
    defaultDurationDays: 28,
    recurrence: 'none',
    themeId: 'minimal',
    progressVisual: 'bar',
    notes: 'Use weekly review checkpoints.',
  },
  {
    id: 'tax-season',
    title: 'Tax Submission',
    icon: '🧾',
    description: 'Recurring yearly tax filing countdown.',
    mode: 'countdown',
    defaultDurationDays: 200,
    recurrence: 'yearly',
    themeId: 'grid',
    progressVisual: 'bar',
    notes: 'Set reminder one week before deadline.',
  },
  {
    id: 'retirement',
    title: 'Retirement',
    icon: '🌅',
    description: 'Long-term life goal countdown.',
    mode: 'countdown',
    defaultDurationDays: 3650,
    recurrence: 'none',
    themeId: 'neon',
    progressVisual: 'ring',
    notes: 'Visualize the remaining journey with yearly progress.',
  },
  {
    id: 'habit-weekly',
    title: 'Weekly Habit Sprint',
    icon: '🏋️',
    description: 'A repeating weekly cycle for habits.',
    mode: 'countdown',
    defaultDurationDays: 7,
    recurrence: 'weekly',
    themeId: 'retro',
    progressVisual: 'bar',
    notes: 'Good for gym or content routines.',
  },
  {
    id: 'new-job',
    title: 'New Job Start',
    icon: '💼',
    description: 'Countdown to your first day.',
    mode: 'countdown',
    defaultDurationDays: 60,
    recurrence: 'none',
    themeId: 'swiss',
    progressVisual: 'ring',
    notes: 'Track onboarding tasks and preparations.',
  },
];
